# This file was generated by GoReleaser. DO NOT EDIT.
class Akash < Formula
  desc "Blockchain-powered decentralized compute platform"
  homepage "https://akash.network"
  version "0.7.21-doubletap.rc23"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ovrclk/akash/releases/download/v0.7.21-doubletap.rc23/akash_0.7.21-doubletap.rc23_darwin_amd64.zip"
    sha256 "0047f9566447fe72f3dd01cc7611a1cbe28e7f084f8ad3c97c3d1830f412375b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ovrclk/akash/releases/download/v0.7.21-doubletap.rc23/akash_0.7.21-doubletap.rc23_linux_amd64.zip"
      sha256 "5ae09094e6cb6d5af37295d618fe0b04328565d3cb6dee297c45dc352403ee12"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ovrclk/akash/releases/download/v0.7.21-doubletap.rc23/akash_0.7.21-doubletap.rc23_linux_arm64.zip"
        sha256 "c1281a90a26051f795f317bc2c50ba2b12dad7aae3326fa5fd73a2e3e0dc5227"
      else
      end
    end
  end

  def install
    bin.install "akash"
  end
end
